package fr.ul.miage.bibliotheque.entite;
// Generated 8 oct. 2018 10:15:55 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Exemplaire generated by hbm2java
 */
@Entity
@Table(name = "exemplaire", catalog = "bibliotheque")
public class Exemplaire implements java.io.Serializable {

	private Integer id;
	private Etat etat;
	private Oeuvre oeuvre;
	private Set<Emprunt> emprunts = new HashSet<Emprunt>(0);

	public Exemplaire() {
	}

	public Exemplaire(Etat etat, Oeuvre oeuvre) {
		this.etat = etat;
		this.oeuvre = oeuvre;
	}

	public Exemplaire(Etat etat, Oeuvre oeuvre, Set<Emprunt> emprunts) {
		this.etat = etat;
		this.oeuvre = oeuvre;
		this.emprunts = emprunts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etat", nullable = false)
	public Etat getEtat() {
		return this.etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_oeuvre", nullable = false)
	public Oeuvre getOeuvre() {
		return this.oeuvre;
	}

	public void setOeuvre(Oeuvre oeuvre) {
		this.oeuvre = oeuvre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exemplaire")
	public Set<Emprunt> getEmprunts() {
		return this.emprunts;
	}

	public void setEmprunts(Set<Emprunt> emprunts) {
		this.emprunts = emprunts;
	}

}
