package fr.ul.miage.bibliotheque.entite;
// Generated 8 oct. 2018 10:15:55 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Oeuvre generated by hbm2java
 */
@Entity
@Table(name = "oeuvre", catalog = "bibliotheque")
public class Oeuvre implements java.io.Serializable {

	private Integer id;
	private TypeOeuvre typeOeuvre;
	private String titre;
	private String isbn;
	private Date dateCreation;
	private int nbResa;
	private Set<Auteur> auteurs = new HashSet<Auteur>(0);
	private Set<Exemplaire> exemplaires = new HashSet<Exemplaire>(0);
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Oeuvre() {
	}

	public Oeuvre(TypeOeuvre typeOeuvre, String titre, String isbn, int nbResa) {
		this.typeOeuvre = typeOeuvre;
		this.titre = titre;
		this.isbn = isbn;
		this.nbResa = nbResa;
	}

	public Oeuvre(TypeOeuvre typeOeuvre, String titre, String isbn, Date dateCreation, int nbResa, Set<Auteur> auteurs,
			Set<Exemplaire> exemplaires, Set<Reservation> reservations) {
		this.typeOeuvre = typeOeuvre;
		this.titre = titre;
		this.isbn = isbn;
		this.dateCreation = dateCreation;
		this.nbResa = nbResa;
		this.auteurs = auteurs;
		this.exemplaires = exemplaires;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_oeuvre", nullable = false)
	public TypeOeuvre getTypeOeuvre() {
		return this.typeOeuvre;
	}

	public void setTypeOeuvre(TypeOeuvre typeOeuvre) {
		this.typeOeuvre = typeOeuvre;
	}

	@Column(name = "titre", nullable = false, length = 100)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "ISBN", nullable = false, length = 100)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_creation", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "nb_resa", nullable = false)
	public int getNbResa() {
		return this.nbResa;
	}

	public void setNbResa(int nbResa) {
		this.nbResa = nbResa;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "auteur_has_oeuvre", catalog = "bibliotheque", joinColumns = {
			@JoinColumn(name = "oeuvre_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "auteur_id", nullable = false, updatable = false) })
	public Set<Auteur> getAuteurs() {
		return this.auteurs;
	}

	public void setAuteurs(Set<Auteur> auteurs) {
		this.auteurs = auteurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oeuvre")
	public Set<Exemplaire> getExemplaires() {
		return this.exemplaires;
	}

	public void setExemplaires(Set<Exemplaire> exemplaires) {
		this.exemplaires = exemplaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oeuvre")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
