package fr.ul.miage.bibliotheque.entite;
// Generated 8 oct. 2018 10:15:55 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "bibliotheque")
public class Reservation implements java.io.Serializable {

	private Integer id;
	private Oeuvre oeuvre;
	private Usager usager;
	private Date dateReservation;
	private int reservationAnnule;

	public Reservation() {
	}

	public Reservation(Oeuvre oeuvre, Usager usager, Date dateReservation, int reservationAnnule) {
		this.oeuvre = oeuvre;
		this.usager = usager;
		this.dateReservation = dateReservation;
		this.reservationAnnule = reservationAnnule;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_oeuvre", nullable = false)
	public Oeuvre getOeuvre() {
		return this.oeuvre;
	}

	public void setOeuvre(Oeuvre oeuvre) {
		this.oeuvre = oeuvre;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_usager", nullable = false)
	public Usager getUsager() {
		return this.usager;
	}

	public void setUsager(Usager usager) {
		this.usager = usager;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_reservation", nullable = false, length = 19)
	public Date getDateReservation() {
		return this.dateReservation;
	}

	public void setDateReservation(Date dateReservation) {
		this.dateReservation = dateReservation;
	}

	@Column(name = "reservation_annule", nullable = false)
	public int getReservationAnnule() {
		return this.reservationAnnule;
	}

	public void setReservationAnnule(int reservationAnnule) {
		this.reservationAnnule = reservationAnnule;
	}
	
	public String toString() {
		return usager.getNom() + " - " + oeuvre.getTitre();
	}

}
