package fr.ul.miage.bibliotheque.entite;
// Generated 3 oct. 2018 12:26:21 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TypeOeuvre generated by hbm2java
 */
@Entity
@Table(name = "type_oeuvre", catalog = "bibliotheque", uniqueConstraints = @UniqueConstraint(columnNames = "libelle"))
public class TypeOeuvre implements java.io.Serializable {

	private Integer id;
	private String libelle;
	private Set<Oeuvre> oeuvres = new HashSet<Oeuvre>(0);

	public TypeOeuvre() {
	}

	public TypeOeuvre(String libelle) {
		this.libelle = libelle;
	}

	public TypeOeuvre(String libelle, Set<Oeuvre> oeuvres) {
		this.libelle = libelle;
		this.oeuvres = oeuvres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "libelle", unique = true, nullable = false, length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeOeuvre")
	public Set<Oeuvre> getOeuvres() {
		return this.oeuvres;
	}

	public void setOeuvres(Set<Oeuvre> oeuvres) {
		this.oeuvres = oeuvres;
	}

}
